"""initial migration

Revision ID: 51ce9fa91bed
Revises: 
Create Date: 2026-03-25 09:42:53.223439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ce9fa91bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_client_tokens_api_key_id'), table_name='api_client_tokens')
    op.drop_table('api_client_tokens')
    op.alter_column('admins', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('internal', 'external', name='admintype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='admins')
    op.drop_index(op.f('ix_users_username'), table_name='admins')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_password_reset_token'), 'admins', ['password_reset_token'], unique=True)
    op.create_index(op.f('ix_admins_role_id'), 'admins', ['role_id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_foreign_key(None, 'admins', 'roles', ['role_id'], ['id'])
    op.alter_column('api_keys', 'key_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('api_keys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(op.f('uq_api_keys_key_id'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.drop_constraint(op.f('permissions_action_resource_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_action_resource_key'), 'permissions', ['action', 'resource'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.create_unique_constraint(op.f('uq_api_keys_key_id'), 'api_keys', ['key_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('api_keys', 'key_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_role_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_password_reset_token'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_index(op.f('ix_users_username'), 'admins', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'admins', ['email'], unique=True)
    op.alter_column('admins', 'type',
               existing_type=sa.Enum('internal', 'external', name='admintype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('api_client_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() + '00:04:00'::interval)"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_client_tokens_pkey'))
    )
    op.create_index(op.f('ix_api_client_tokens_api_key_id'), 'api_client_tokens', ['api_key_id'], unique=False)
    # ### end Alembic commands ###
